# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 559)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pokemonLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pokemonLineEdit.setObjectName("pokemonLineEdit")
        self.gridLayout.addWidget(self.pokemonLineEdit, 0, 1, 1, 1)
        self.pokemonLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pokemonLabel.setFont(font)
        self.pokemonLabel.setStyleSheet("")
        self.pokemonLabel.setObjectName("pokemonLabel")
        self.gridLayout.addWidget(self.pokemonLabel, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("selection-background-color: rgb(76, 76, 76);")
        self.tab.setObjectName("tab")
        self.sftBallDropdown = QtWidgets.QComboBox(self.tab)
        self.sftBallDropdown.setGeometry(QtCore.QRect(20, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sftBallDropdown.setFont(font)
        self.sftBallDropdown.setObjectName("sftBallDropdown")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.setItemText(0, "")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallDropdown.addItem("")
        self.sftBallLabel = QtWidgets.QLabel(self.tab)
        self.sftBallLabel.setGeometry(QtCore.QRect(20, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftBallLabel.setFont(font)
        self.sftBallLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sftBallLabel.setObjectName("sftBallLabel")
        self.sftNatureDropdown = QtWidgets.QComboBox(self.tab)
        self.sftNatureDropdown.setGeometry(QtCore.QRect(170, 40, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sftNatureDropdown.setFont(font)
        self.sftNatureDropdown.setMaxVisibleItems(10)
        self.sftNatureDropdown.setObjectName("sftNatureDropdown")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.setItemText(0, "")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureDropdown.addItem("")
        self.sftNatureLabel = QtWidgets.QLabel(self.tab)
        self.sftNatureLabel.setGeometry(QtCore.QRect(170, 12, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftNatureLabel.setFont(font)
        self.sftNatureLabel.setObjectName("sftNatureLabel")
        self.sftAbilityLabel = QtWidgets.QLabel(self.tab)
        self.sftAbilityLabel.setGeometry(QtCore.QRect(20, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftAbilityLabel.setFont(font)
        self.sftAbilityLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sftAbilityLabel.setObjectName("sftAbilityLabel")
        self.sftAbilityDropdown = QtWidgets.QComboBox(self.tab)
        self.sftAbilityDropdown.setGeometry(QtCore.QRect(20, 110, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sftAbilityDropdown.setFont(font)
        self.sftAbilityDropdown.setObjectName("sftAbilityDropdown")
        self.sftAbilityDropdown.addItem("")
        self.sftAbilityDropdown.setItemText(0, "")
        self.sftAbilityDropdown.addItem("")
        self.sftAbilityDropdown.addItem("")
        self.sftAbilityDropdown.addItem("")
        self.sftGMaxRadioButton = QtWidgets.QRadioButton(self.tab)
        self.sftGMaxRadioButton.setGeometry(QtCore.QRect(350, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sftGMaxRadioButton.setFont(font)
        self.sftGMaxRadioButton.setText("")
        self.sftGMaxRadioButton.setAutoExclusive(False)
        self.sftGMaxRadioButton.setObjectName("sftGMaxRadioButton")
        self.sftGMaxLabel = QtWidgets.QLabel(self.tab)
        self.sftGMaxLabel.setGeometry(QtCore.QRect(320, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftGMaxLabel.setFont(font)
        self.sftGMaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sftGMaxLabel.setObjectName("sftGMaxLabel")
        self.sftIvBox = QtWidgets.QGroupBox(self.tab)
        self.sftIvBox.setGeometry(QtCore.QRect(400, 30, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftIvBox.setFont(font)
        self.sftIvBox.setObjectName("sftIvBox")
        self.sftHpRadioButton = QtWidgets.QRadioButton(self.sftIvBox)
        self.sftHpRadioButton.setGeometry(QtCore.QRect(20, 40, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sftHpRadioButton.setFont(font)
        self.sftHpRadioButton.setStyleSheet("")
        self.sftHpRadioButton.setAutoExclusive(False)
        self.sftHpRadioButton.setObjectName("sftHpRadioButton")
        self.sftAtkRadioButton = QtWidgets.QRadioButton(self.sftIvBox)
        self.sftAtkRadioButton.setGeometry(QtCore.QRect(20, 60, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sftAtkRadioButton.setFont(font)
        self.sftAtkRadioButton.setStyleSheet("")
        self.sftAtkRadioButton.setAutoExclusive(False)
        self.sftAtkRadioButton.setObjectName("sftAtkRadioButton")
        self.sftDefRadioButton = QtWidgets.QRadioButton(self.sftIvBox)
        self.sftDefRadioButton.setGeometry(QtCore.QRect(20, 80, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sftDefRadioButton.setFont(font)
        self.sftDefRadioButton.setStyleSheet("")
        self.sftDefRadioButton.setAutoExclusive(False)
        self.sftDefRadioButton.setObjectName("sftDefRadioButton")
        self.sftSpaRadioButton = QtWidgets.QRadioButton(self.sftIvBox)
        self.sftSpaRadioButton.setGeometry(QtCore.QRect(110, 40, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sftSpaRadioButton.setFont(font)
        self.sftSpaRadioButton.setStyleSheet("")
        self.sftSpaRadioButton.setAutoExclusive(False)
        self.sftSpaRadioButton.setObjectName("sftSpaRadioButton")
        self.sftSpdRadioButton = QtWidgets.QRadioButton(self.sftIvBox)
        self.sftSpdRadioButton.setGeometry(QtCore.QRect(110, 60, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sftSpdRadioButton.setFont(font)
        self.sftSpdRadioButton.setStyleSheet("")
        self.sftSpdRadioButton.setAutoExclusive(False)
        self.sftSpdRadioButton.setObjectName("sftSpdRadioButton")
        self.sftSpeRadioButton = QtWidgets.QRadioButton(self.sftIvBox)
        self.sftSpeRadioButton.setGeometry(QtCore.QRect(110, 80, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sftSpeRadioButton.setFont(font)
        self.sftSpeRadioButton.setStyleSheet("")
        self.sftSpeRadioButton.setAutoExclusive(False)
        self.sftSpeRadioButton.setObjectName("sftSpeRadioButton")
        self.sftZeroSpeedLabel = QtWidgets.QLabel(self.tab)
        self.sftZeroSpeedLabel.setGeometry(QtCore.QRect(320, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftZeroSpeedLabel.setFont(font)
        self.sftZeroSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sftZeroSpeedLabel.setObjectName("sftZeroSpeedLabel")
        self.sftZeroSpeedRadioButton = QtWidgets.QRadioButton(self.tab)
        self.sftZeroSpeedRadioButton.setGeometry(QtCore.QRect(350, 110, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sftZeroSpeedRadioButton.setFont(font)
        self.sftZeroSpeedRadioButton.setText("")
        self.sftZeroSpeedRadioButton.setAutoExclusive(False)
        self.sftZeroSpeedRadioButton.setObjectName("sftZeroSpeedRadioButton")
        self.sftOtLabel = QtWidgets.QLabel(self.tab)
        self.sftOtLabel.setGeometry(QtCore.QRect(160, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftOtLabel.setFont(font)
        self.sftOtLabel.setObjectName("sftOtLabel")
        self.sftOtLineEdit = QtWidgets.QLineEdit(self.tab)
        self.sftOtLineEdit.setGeometry(QtCore.QRect(190, 80, 121, 20))
        self.sftOtLineEdit.setObjectName("sftOtLineEdit")
        self.sftIdLabel = QtWidgets.QLabel(self.tab)
        self.sftIdLabel.setGeometry(QtCore.QRect(160, 110, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftIdLabel.setFont(font)
        self.sftIdLabel.setObjectName("sftIdLabel")
        self.sftIdLineEdit = QtWidgets.QLineEdit(self.tab)
        self.sftIdLineEdit.setGeometry(QtCore.QRect(190, 110, 121, 20))
        self.sftIdLineEdit.setObjectName("sftIdLineEdit")
        self.sftSubmitPushButton = QtWidgets.QPushButton(self.tab)
        self.sftSubmitPushButton.setGeometry(QtCore.QRect(360, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftSubmitPushButton.setFont(font)
        self.sftSubmitPushButton.setObjectName("sftSubmitPushButton")
        self.sftObtainedLabel = QtWidgets.QLabel(self.tab)
        self.sftObtainedLabel.setGeometry(QtCore.QRect(20, 230, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftObtainedLabel.setFont(font)
        self.sftObtainedLabel.setObjectName("sftObtainedLabel")
        self.sftObtainedLineEdit = QtWidgets.QLineEdit(self.tab)
        self.sftObtainedLineEdit.setGeometry(QtCore.QRect(90, 230, 191, 20))
        self.sftObtainedLineEdit.setObjectName("sftObtainedLineEdit")
        self.sftImage = QtWidgets.QLabel(self.tab)
        self.sftImage.setGeometry(QtCore.QRect(600, 30, 221, 251))
        self.sftImage.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.sftImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sftImage.setText("")
        self.sftImage.setObjectName("sftImage")
        self.sftGenderComboBox = QtWidgets.QComboBox(self.tab)
        self.sftGenderComboBox.setGeometry(QtCore.QRect(160, 180, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sftGenderComboBox.setFont(font)
        self.sftGenderComboBox.setObjectName("sftGenderComboBox")
        self.sftGenderComboBox.addItem("")
        self.sftGenderComboBox.setItemText(0, "")
        self.sftGenderComboBox.addItem("")
        self.sftGenderComboBox.addItem("")
        self.sftGenderComboBox.addItem("")
        self.sftGenderLabel = QtWidgets.QLabel(self.tab)
        self.sftGenderLabel.setGeometry(QtCore.QRect(160, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftGenderLabel.setFont(font)
        self.sftGenderLabel.setObjectName("sftGenderLabel")
        self.sftSTypeComboBox = QtWidgets.QComboBox(self.tab)
        self.sftSTypeComboBox.setGeometry(QtCore.QRect(20, 180, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sftSTypeComboBox.setFont(font)
        self.sftSTypeComboBox.setObjectName("sftSTypeComboBox")
        self.sftSTypeComboBox.addItem("")
        self.sftSTypeComboBox.setItemText(0, "")
        self.sftSTypeComboBox.addItem("")
        self.sftSTypeComboBox.addItem("")
        self.sftSTypeLabel = QtWidgets.QLabel(self.tab)
        self.sftSTypeLabel.setGeometry(QtCore.QRect(20, 150, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sftSTypeLabel.setFont(font)
        self.sftSTypeLabel.setObjectName("sftSTypeLabel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.aftBallDropdown = QtWidgets.QComboBox(self.tab_2)
        self.aftBallDropdown.setGeometry(QtCore.QRect(20, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aftBallDropdown.setFont(font)
        self.aftBallDropdown.setObjectName("aftBallDropdown")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.setItemText(0, "")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftBallDropdown.addItem("")
        self.aftGMaxRadioButton = QtWidgets.QRadioButton(self.tab_2)
        self.aftGMaxRadioButton.setGeometry(QtCore.QRect(360, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.aftGMaxRadioButton.setFont(font)
        self.aftGMaxRadioButton.setText("")
        self.aftGMaxRadioButton.setAutoExclusive(False)
        self.aftGMaxRadioButton.setObjectName("aftGMaxRadioButton")
        self.aftGMaxLabel = QtWidgets.QLabel(self.tab_2)
        self.aftGMaxLabel.setGeometry(QtCore.QRect(330, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftGMaxLabel.setFont(font)
        self.aftGMaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aftGMaxLabel.setObjectName("aftGMaxLabel")
        self.aftAbilityLabel = QtWidgets.QLabel(self.tab_2)
        self.aftAbilityLabel.setGeometry(QtCore.QRect(20, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftAbilityLabel.setFont(font)
        self.aftAbilityLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aftAbilityLabel.setObjectName("aftAbilityLabel")
        self.aftNatureLabel = QtWidgets.QLabel(self.tab_2)
        self.aftNatureLabel.setGeometry(QtCore.QRect(170, 12, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftNatureLabel.setFont(font)
        self.aftNatureLabel.setObjectName("aftNatureLabel")
        self.aftNatureDropdown = QtWidgets.QComboBox(self.tab_2)
        self.aftNatureDropdown.setGeometry(QtCore.QRect(170, 40, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.aftNatureDropdown.setFont(font)
        self.aftNatureDropdown.setObjectName("aftNatureDropdown")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.setItemText(0, "")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftNatureDropdown.addItem("")
        self.aftZeroSpeedLabel = QtWidgets.QLabel(self.tab_2)
        self.aftZeroSpeedLabel.setGeometry(QtCore.QRect(330, 70, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftZeroSpeedLabel.setFont(font)
        self.aftZeroSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aftZeroSpeedLabel.setObjectName("aftZeroSpeedLabel")
        self.aftSubmitPushButton = QtWidgets.QPushButton(self.tab_2)
        self.aftSubmitPushButton.setGeometry(QtCore.QRect(190, 210, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftSubmitPushButton.setFont(font)
        self.aftSubmitPushButton.setObjectName("aftSubmitPushButton")
        self.aftAbilityDropdown = QtWidgets.QComboBox(self.tab_2)
        self.aftAbilityDropdown.setGeometry(QtCore.QRect(20, 130, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aftAbilityDropdown.setFont(font)
        self.aftAbilityDropdown.setObjectName("aftAbilityDropdown")
        self.aftAbilityDropdown.addItem("")
        self.aftAbilityDropdown.setItemText(0, "")
        self.aftAbilityDropdown.addItem("")
        self.aftAbilityDropdown.addItem("")
        self.aftAbilityDropdown.addItem("")
        self.aftBallLabel = QtWidgets.QLabel(self.tab_2)
        self.aftBallLabel.setGeometry(QtCore.QRect(20, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftBallLabel.setFont(font)
        self.aftBallLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.aftBallLabel.setObjectName("aftBallLabel")
        self.aftZeroSpeedRadioButton = QtWidgets.QRadioButton(self.tab_2)
        self.aftZeroSpeedRadioButton.setGeometry(QtCore.QRect(360, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.aftZeroSpeedRadioButton.setFont(font)
        self.aftZeroSpeedRadioButton.setText("")
        self.aftZeroSpeedRadioButton.setAutoExclusive(False)
        self.aftZeroSpeedRadioButton.setObjectName("aftZeroSpeedRadioButton")
        self.aftIvDropdown = QtWidgets.QComboBox(self.tab_2)
        self.aftIvDropdown.setGeometry(QtCore.QRect(170, 130, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aftIvDropdown.setFont(font)
        self.aftIvDropdown.setObjectName("aftIvDropdown")
        self.aftIvDropdown.addItem("")
        self.aftIvDropdown.setItemText(0, "")
        self.aftIvDropdown.addItem("")
        self.aftIvDropdown.addItem("")
        self.aftIvDropdown.addItem("")
        self.aftIvDropdown.addItem("")
        self.aftIvDropdown.addItem("")
        self.aftIvDropdown.addItem("")
        self.aftIvDropdown.addItem("")
        self.aftIvLabel = QtWidgets.QLabel(self.tab_2)
        self.aftIvLabel.setGeometry(QtCore.QRect(170, 93, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftIvLabel.setFont(font)
        self.aftIvLabel.setObjectName("aftIvLabel")
        self.aftStockLabel = QtWidgets.QLabel(self.tab_2)
        self.aftStockLabel.setGeometry(QtCore.QRect(320, 130, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.aftStockLabel.setFont(font)
        self.aftStockLabel.setObjectName("aftStockLabel")
        self.aftStockSpinBox = QtWidgets.QSpinBox(self.tab_2)
        self.aftStockSpinBox.setGeometry(QtCore.QRect(380, 130, 42, 22))
        self.aftStockSpinBox.setObjectName("aftStockSpinBox")
        self.aftImage = QtWidgets.QLabel(self.tab_2)
        self.aftImage.setGeometry(QtCore.QRect(486, 22, 221, 251))
        self.aftImage.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.aftImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aftImage.setText("")
        self.aftImage.setObjectName("aftImage")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.shinyZeroSpeedRadioButton = QtWidgets.QRadioButton(self.tab_3)
        self.shinyZeroSpeedRadioButton.setGeometry(QtCore.QRect(350, 110, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shinyZeroSpeedRadioButton.setFont(font)
        self.shinyZeroSpeedRadioButton.setText("")
        self.shinyZeroSpeedRadioButton.setAutoExclusive(False)
        self.shinyZeroSpeedRadioButton.setObjectName("shinyZeroSpeedRadioButton")
        self.shinyIvBox = QtWidgets.QGroupBox(self.tab_3)
        self.shinyIvBox.setGeometry(QtCore.QRect(400, 30, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyIvBox.setFont(font)
        self.shinyIvBox.setObjectName("shinyIvBox")
        self.shinyHpRadioButton = QtWidgets.QRadioButton(self.shinyIvBox)
        self.shinyHpRadioButton.setGeometry(QtCore.QRect(20, 40, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shinyHpRadioButton.setFont(font)
        self.shinyHpRadioButton.setAutoExclusive(False)
        self.shinyHpRadioButton.setObjectName("shinyHpRadioButton")
        self.shinyAtkRadioButton = QtWidgets.QRadioButton(self.shinyIvBox)
        self.shinyAtkRadioButton.setGeometry(QtCore.QRect(20, 60, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shinyAtkRadioButton.setFont(font)
        self.shinyAtkRadioButton.setAutoExclusive(False)
        self.shinyAtkRadioButton.setObjectName("shinyAtkRadioButton")
        self.shinyDefRadioButton = QtWidgets.QRadioButton(self.shinyIvBox)
        self.shinyDefRadioButton.setGeometry(QtCore.QRect(20, 80, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shinyDefRadioButton.setFont(font)
        self.shinyDefRadioButton.setAutoExclusive(False)
        self.shinyDefRadioButton.setObjectName("shinyDefRadioButton")
        self.shinySpaRadioButton = QtWidgets.QRadioButton(self.shinyIvBox)
        self.shinySpaRadioButton.setGeometry(QtCore.QRect(110, 40, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shinySpaRadioButton.setFont(font)
        self.shinySpaRadioButton.setAutoExclusive(False)
        self.shinySpaRadioButton.setObjectName("shinySpaRadioButton")
        self.shinySpdRadioButton = QtWidgets.QRadioButton(self.shinyIvBox)
        self.shinySpdRadioButton.setGeometry(QtCore.QRect(110, 60, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shinySpdRadioButton.setFont(font)
        self.shinySpdRadioButton.setAutoExclusive(False)
        self.shinySpdRadioButton.setObjectName("shinySpdRadioButton")
        self.shinySpeRadioButton = QtWidgets.QRadioButton(self.shinyIvBox)
        self.shinySpeRadioButton.setGeometry(QtCore.QRect(110, 80, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shinySpeRadioButton.setFont(font)
        self.shinySpeRadioButton.setAutoExclusive(False)
        self.shinySpeRadioButton.setObjectName("shinySpeRadioButton")
        self.shinyAbilityLabel = QtWidgets.QLabel(self.tab_3)
        self.shinyAbilityLabel.setGeometry(QtCore.QRect(20, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyAbilityLabel.setFont(font)
        self.shinyAbilityLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shinyAbilityLabel.setObjectName("shinyAbilityLabel")
        self.shinyGMaxLabel = QtWidgets.QLabel(self.tab_3)
        self.shinyGMaxLabel.setGeometry(QtCore.QRect(320, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyGMaxLabel.setFont(font)
        self.shinyGMaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.shinyGMaxLabel.setObjectName("shinyGMaxLabel")
        self.shinyZeroSpeedLabel = QtWidgets.QLabel(self.tab_3)
        self.shinyZeroSpeedLabel.setGeometry(QtCore.QRect(320, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyZeroSpeedLabel.setFont(font)
        self.shinyZeroSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.shinyZeroSpeedLabel.setObjectName("shinyZeroSpeedLabel")
        self.shinyImage = QtWidgets.QLabel(self.tab_3)
        self.shinyImage.setGeometry(QtCore.QRect(600, 30, 221, 251))
        self.shinyImage.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.shinyImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shinyImage.setText("")
        self.shinyImage.setObjectName("shinyImage")
        self.shinyGMaxRadioButton = QtWidgets.QRadioButton(self.tab_3)
        self.shinyGMaxRadioButton.setGeometry(QtCore.QRect(350, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.shinyGMaxRadioButton.setFont(font)
        self.shinyGMaxRadioButton.setText("")
        self.shinyGMaxRadioButton.setAutoExclusive(False)
        self.shinyGMaxRadioButton.setObjectName("shinyGMaxRadioButton")
        self.shinyBallLabel = QtWidgets.QLabel(self.tab_3)
        self.shinyBallLabel.setGeometry(QtCore.QRect(20, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyBallLabel.setFont(font)
        self.shinyBallLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shinyBallLabel.setObjectName("shinyBallLabel")
        self.shinyNatureDropdown = QtWidgets.QComboBox(self.tab_3)
        self.shinyNatureDropdown.setGeometry(QtCore.QRect(170, 40, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.shinyNatureDropdown.setFont(font)
        self.shinyNatureDropdown.setObjectName("shinyNatureDropdown")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.setItemText(0, "")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinyNatureDropdown.addItem("")
        self.shinySubmitPushButton = QtWidgets.QPushButton(self.tab_3)
        self.shinySubmitPushButton.setGeometry(QtCore.QRect(360, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinySubmitPushButton.setFont(font)
        self.shinySubmitPushButton.setObjectName("shinySubmitPushButton")
        self.shinyAbilityDropdown = QtWidgets.QComboBox(self.tab_3)
        self.shinyAbilityDropdown.setGeometry(QtCore.QRect(20, 130, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shinyAbilityDropdown.setFont(font)
        self.shinyAbilityDropdown.setObjectName("shinyAbilityDropdown")
        self.shinyAbilityDropdown.addItem("")
        self.shinyAbilityDropdown.setItemText(0, "")
        self.shinyAbilityDropdown.addItem("")
        self.shinyAbilityDropdown.addItem("")
        self.shinyAbilityDropdown.addItem("")
        self.shinyBallDropdown = QtWidgets.QComboBox(self.tab_3)
        self.shinyBallDropdown.setGeometry(QtCore.QRect(20, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shinyBallDropdown.setFont(font)
        self.shinyBallDropdown.setObjectName("shinyBallDropdown")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.setItemText(0, "")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyBallDropdown.addItem("")
        self.shinyNatureLabel = QtWidgets.QLabel(self.tab_3)
        self.shinyNatureLabel.setGeometry(QtCore.QRect(170, 12, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyNatureLabel.setFont(font)
        self.shinyNatureLabel.setObjectName("shinyNatureLabel")
        self.shinyNicknameLabel = QtWidgets.QLabel(self.tab_3)
        self.shinyNicknameLabel.setGeometry(QtCore.QRect(170, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyNicknameLabel.setFont(font)
        self.shinyNicknameLabel.setObjectName("shinyNicknameLabel")
        self.shinyNicknameLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.shinyNicknameLineEdit.setGeometry(QtCore.QRect(170, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.shinyNicknameLineEdit.setFont(font)
        self.shinyNicknameLineEdit.setText("")
        self.shinyNicknameLineEdit.setObjectName("shinyNicknameLineEdit")
        self.shinySTypeLabel = QtWidgets.QLabel(self.tab_3)
        self.shinySTypeLabel.setGeometry(QtCore.QRect(20, 173, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinySTypeLabel.setFont(font)
        self.shinySTypeLabel.setObjectName("shinySTypeLabel")
        self.shinySTypeComboBox = QtWidgets.QComboBox(self.tab_3)
        self.shinySTypeComboBox.setGeometry(QtCore.QRect(20, 200, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shinySTypeComboBox.setFont(font)
        self.shinySTypeComboBox.setObjectName("shinySTypeComboBox")
        self.shinySTypeComboBox.addItem("")
        self.shinySTypeComboBox.setItemText(0, "")
        self.shinySTypeComboBox.addItem("")
        self.shinySTypeComboBox.addItem("")
        self.shinyGenderLabel = QtWidgets.QLabel(self.tab_3)
        self.shinyGenderLabel.setGeometry(QtCore.QRect(170, 173, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.shinyGenderLabel.setFont(font)
        self.shinyGenderLabel.setObjectName("shinyGenderLabel")
        self.shinyGenderComboBox = QtWidgets.QComboBox(self.tab_3)
        self.shinyGenderComboBox.setGeometry(QtCore.QRect(170, 200, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shinyGenderComboBox.setFont(font)
        self.shinyGenderComboBox.setObjectName("shinyGenderComboBox")
        self.shinyGenderComboBox.addItem("")
        self.shinyGenderComboBox.setItemText(0, "")
        self.shinyGenderComboBox.addItem("")
        self.shinyGenderComboBox.addItem("")
        self.shinyGenderComboBox.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.battleAbilityLabel = QtWidgets.QLabel(self.tab_4)
        self.battleAbilityLabel.setGeometry(QtCore.QRect(20, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleAbilityLabel.setFont(font)
        self.battleAbilityLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.battleAbilityLabel.setObjectName("battleAbilityLabel")
        self.battleBallDropdown = QtWidgets.QComboBox(self.tab_4)
        self.battleBallDropdown.setGeometry(QtCore.QRect(20, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.battleBallDropdown.setFont(font)
        self.battleBallDropdown.setObjectName("battleBallDropdown")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.setItemText(0, "")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleBallDropdown.addItem("")
        self.battleNatureLabel = QtWidgets.QLabel(self.tab_4)
        self.battleNatureLabel.setGeometry(QtCore.QRect(170, 12, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleNatureLabel.setFont(font)
        self.battleNatureLabel.setObjectName("battleNatureLabel")
        self.battleZeroSpeedLabel = QtWidgets.QLabel(self.tab_4)
        self.battleZeroSpeedLabel.setGeometry(QtCore.QRect(320, 67, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleZeroSpeedLabel.setFont(font)
        self.battleZeroSpeedLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.battleZeroSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.battleZeroSpeedLabel.setObjectName("battleZeroSpeedLabel")
        self.battleNatureDropdown = QtWidgets.QComboBox(self.tab_4)
        self.battleNatureDropdown.setGeometry(QtCore.QRect(170, 40, 141, 22))
        self.battleNatureDropdown.setObjectName("battleNatureDropdown")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.setItemText(0, "")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNatureDropdown.addItem("")
        self.battleNicknameLineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.battleNicknameLineEdit.setGeometry(QtCore.QRect(170, 110, 141, 21))
        self.battleNicknameLineEdit.setText("")
        self.battleNicknameLineEdit.setObjectName("battleNicknameLineEdit")
        self.battleGMaxLabel = QtWidgets.QLabel(self.tab_4)
        self.battleGMaxLabel.setGeometry(QtCore.QRect(320, 17, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleGMaxLabel.setFont(font)
        self.battleGMaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.battleGMaxLabel.setObjectName("battleGMaxLabel")
        self.battleGMaxRadioButton = QtWidgets.QRadioButton(self.tab_4)
        self.battleGMaxRadioButton.setGeometry(QtCore.QRect(350, 37, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.battleGMaxRadioButton.setFont(font)
        self.battleGMaxRadioButton.setText("")
        self.battleGMaxRadioButton.setAutoExclusive(False)
        self.battleGMaxRadioButton.setObjectName("battleGMaxRadioButton")
        self.battleAbilityDropdown = QtWidgets.QComboBox(self.tab_4)
        self.battleAbilityDropdown.setGeometry(QtCore.QRect(20, 110, 131, 22))
        self.battleAbilityDropdown.setObjectName("battleAbilityDropdown")
        self.battleAbilityDropdown.addItem("")
        self.battleAbilityDropdown.setItemText(0, "")
        self.battleAbilityDropdown.addItem("")
        self.battleAbilityDropdown.addItem("")
        self.battleAbilityDropdown.addItem("")
        self.battleBallLabel = QtWidgets.QLabel(self.tab_4)
        self.battleBallLabel.setGeometry(QtCore.QRect(20, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleBallLabel.setFont(font)
        self.battleBallLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.battleBallLabel.setObjectName("battleBallLabel")
        self.battleIvBox = QtWidgets.QGroupBox(self.tab_4)
        self.battleIvBox.setGeometry(QtCore.QRect(400, 30, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleIvBox.setFont(font)
        self.battleIvBox.setObjectName("battleIvBox")
        self.battleHpRadioButton = QtWidgets.QRadioButton(self.battleIvBox)
        self.battleHpRadioButton.setGeometry(QtCore.QRect(20, 40, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.battleHpRadioButton.setFont(font)
        self.battleHpRadioButton.setAutoExclusive(False)
        self.battleHpRadioButton.setObjectName("battleHpRadioButton")
        self.battleAtkRadioButton = QtWidgets.QRadioButton(self.battleIvBox)
        self.battleAtkRadioButton.setGeometry(QtCore.QRect(20, 60, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.battleAtkRadioButton.setFont(font)
        self.battleAtkRadioButton.setAutoExclusive(False)
        self.battleAtkRadioButton.setObjectName("battleAtkRadioButton")
        self.battleDefRadioButton = QtWidgets.QRadioButton(self.battleIvBox)
        self.battleDefRadioButton.setGeometry(QtCore.QRect(20, 80, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.battleDefRadioButton.setFont(font)
        self.battleDefRadioButton.setAutoExclusive(False)
        self.battleDefRadioButton.setObjectName("battleDefRadioButton")
        self.battleSpaRadioButton = QtWidgets.QRadioButton(self.battleIvBox)
        self.battleSpaRadioButton.setGeometry(QtCore.QRect(110, 40, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.battleSpaRadioButton.setFont(font)
        self.battleSpaRadioButton.setAutoExclusive(False)
        self.battleSpaRadioButton.setObjectName("battleSpaRadioButton")
        self.battleSpdRadioButton = QtWidgets.QRadioButton(self.battleIvBox)
        self.battleSpdRadioButton.setGeometry(QtCore.QRect(110, 60, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.battleSpdRadioButton.setFont(font)
        self.battleSpdRadioButton.setAutoExclusive(False)
        self.battleSpdRadioButton.setObjectName("battleSpdRadioButton")
        self.battleSpeRadioButton = QtWidgets.QRadioButton(self.battleIvBox)
        self.battleSpeRadioButton.setGeometry(QtCore.QRect(110, 80, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.battleSpeRadioButton.setFont(font)
        self.battleSpeRadioButton.setAutoExclusive(False)
        self.battleSpeRadioButton.setObjectName("battleSpeRadioButton")
        self.battleNicknameLabel = QtWidgets.QLabel(self.tab_4)
        self.battleNicknameLabel.setGeometry(QtCore.QRect(170, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleNicknameLabel.setFont(font)
        self.battleNicknameLabel.setObjectName("battleNicknameLabel")
        self.battleImage = QtWidgets.QLabel(self.tab_4)
        self.battleImage.setGeometry(QtCore.QRect(600, 30, 221, 251))
        self.battleImage.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.battleImage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.battleImage.setText("")
        self.battleImage.setObjectName("battleImage")
        self.battleSubmitPushButton = QtWidgets.QPushButton(self.tab_4)
        self.battleSubmitPushButton.setGeometry(QtCore.QRect(420, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleSubmitPushButton.setFont(font)
        self.battleSubmitPushButton.setObjectName("battleSubmitPushButton")
        self.battleZeroSpeedRadioButton = QtWidgets.QRadioButton(self.tab_4)
        self.battleZeroSpeedRadioButton.setGeometry(QtCore.QRect(350, 87, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.battleZeroSpeedRadioButton.setFont(font)
        self.battleZeroSpeedRadioButton.setText("")
        self.battleZeroSpeedRadioButton.setAutoExclusive(False)
        self.battleZeroSpeedRadioButton.setObjectName("battleZeroSpeedRadioButton")
        self.battleShinyLabel = QtWidgets.QLabel(self.tab_4)
        self.battleShinyLabel.setGeometry(QtCore.QRect(320, 120, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleShinyLabel.setFont(font)
        self.battleShinyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.battleShinyLabel.setObjectName("battleShinyLabel")
        self.battleShinyRadioButton = QtWidgets.QRadioButton(self.tab_4)
        self.battleShinyRadioButton.setGeometry(QtCore.QRect(350, 140, 21, 17))
        self.battleShinyRadioButton.setText("")
        self.battleShinyRadioButton.setAutoExclusive(False)
        self.battleShinyRadioButton.setObjectName("battleShinyRadioButton")
        self.battleMovesGroupBox = QtWidgets.QGroupBox(self.tab_4)
        self.battleMovesGroupBox.setGeometry(QtCore.QRect(30, 230, 331, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleMovesGroupBox.setFont(font)
        self.battleMovesGroupBox.setObjectName("battleMovesGroupBox")
        self.battleMove1Label = QtWidgets.QLabel(self.battleMovesGroupBox)
        self.battleMove1Label.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.battleMove1Label.setFont(font)
        self.battleMove1Label.setObjectName("battleMove1Label")
        self.battleMove1LineEdit = QtWidgets.QLineEdit(self.battleMovesGroupBox)
        self.battleMove1LineEdit.setGeometry(QtCore.QRect(10, 60, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.battleMove1LineEdit.setFont(font)
        self.battleMove1LineEdit.setObjectName("battleMove1LineEdit")
        self.battleMove2Label = QtWidgets.QLabel(self.battleMovesGroupBox)
        self.battleMove2Label.setGeometry(QtCore.QRect(180, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.battleMove2Label.setFont(font)
        self.battleMove2Label.setObjectName("battleMove2Label")
        self.battleMove2LineEdit = QtWidgets.QLineEdit(self.battleMovesGroupBox)
        self.battleMove2LineEdit.setGeometry(QtCore.QRect(180, 60, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.battleMove2LineEdit.setFont(font)
        self.battleMove2LineEdit.setObjectName("battleMove2LineEdit")
        self.battleMove3LineEdit = QtWidgets.QLineEdit(self.battleMovesGroupBox)
        self.battleMove3LineEdit.setGeometry(QtCore.QRect(10, 120, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.battleMove3LineEdit.setFont(font)
        self.battleMove3LineEdit.setObjectName("battleMove3LineEdit")
        self.battleMove3Label = QtWidgets.QLabel(self.battleMovesGroupBox)
        self.battleMove3Label.setGeometry(QtCore.QRect(10, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.battleMove3Label.setFont(font)
        self.battleMove3Label.setObjectName("battleMove3Label")
        self.battleMove4LineEdit = QtWidgets.QLineEdit(self.battleMovesGroupBox)
        self.battleMove4LineEdit.setGeometry(QtCore.QRect(180, 120, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.battleMove4LineEdit.setFont(font)
        self.battleMove4LineEdit.setText("")
        self.battleMove4LineEdit.setObjectName("battleMove4LineEdit")
        self.battleMove4Label = QtWidgets.QLabel(self.battleMovesGroupBox)
        self.battleMove4Label.setGeometry(QtCore.QRect(180, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.battleMove4Label.setFont(font)
        self.battleMove4Label.setObjectName("battleMove4Label")
        self.battleSTypeLabel = QtWidgets.QLabel(self.tab_4)
        self.battleSTypeLabel.setGeometry(QtCore.QRect(20, 150, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleSTypeLabel.setFont(font)
        self.battleSTypeLabel.setObjectName("battleSTypeLabel")
        self.battleSTypeComboBox = QtWidgets.QComboBox(self.tab_4)
        self.battleSTypeComboBox.setGeometry(QtCore.QRect(20, 180, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.battleSTypeComboBox.setFont(font)
        self.battleSTypeComboBox.setObjectName("battleSTypeComboBox")
        self.battleSTypeComboBox.addItem("")
        self.battleSTypeComboBox.setItemText(0, "")
        self.battleSTypeComboBox.addItem("")
        self.battleSTypeComboBox.addItem("")
        self.battleGenderLabel = QtWidgets.QLabel(self.tab_4)
        self.battleGenderLabel.setGeometry(QtCore.QRect(170, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battleGenderLabel.setFont(font)
        self.battleGenderLabel.setObjectName("battleGenderLabel")
        self.battleGenderComboBox = QtWidgets.QComboBox(self.tab_4)
        self.battleGenderComboBox.setGeometry(QtCore.QRect(170, 180, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.battleGenderComboBox.setFont(font)
        self.battleGenderComboBox.setObjectName("battleGenderComboBox")
        self.battleGenderComboBox.addItem("")
        self.battleGenderComboBox.setItemText(0, "")
        self.battleGenderComboBox.addItem("")
        self.battleGenderComboBox.addItem("")
        self.battleGenderComboBox.addItem("")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.errorLabel, 1, 1, 1, 1)
        self.updateRowsButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateRowsButton.setObjectName("updateRowsButton")
        self.gridLayout.addWidget(self.updateRowsButton, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pokemon Tracker Companion"))
        self.pokemonLabel.setText(_translate("MainWindow", "Pokemon"))
        self.sftBallDropdown.setItemText(1, _translate("MainWindow", "Beast Ball"))
        self.sftBallDropdown.setItemText(2, _translate("MainWindow", "Cherish Ball"))
        self.sftBallDropdown.setItemText(3, _translate("MainWindow", "Dive Ball"))
        self.sftBallDropdown.setItemText(4, _translate("MainWindow", "Dream Ball"))
        self.sftBallDropdown.setItemText(5, _translate("MainWindow", "Dusk Ball"))
        self.sftBallDropdown.setItemText(6, _translate("MainWindow", "Fast Ball"))
        self.sftBallDropdown.setItemText(7, _translate("MainWindow", "Friend Ball"))
        self.sftBallDropdown.setItemText(8, _translate("MainWindow", "Great Ball"))
        self.sftBallDropdown.setItemText(9, _translate("MainWindow", "Heal Ball"))
        self.sftBallDropdown.setItemText(10, _translate("MainWindow", "Heavy Ball"))
        self.sftBallDropdown.setItemText(11, _translate("MainWindow", "Level Ball"))
        self.sftBallDropdown.setItemText(12, _translate("MainWindow", "Love Ball"))
        self.sftBallDropdown.setItemText(13, _translate("MainWindow", "Lure Ball"))
        self.sftBallDropdown.setItemText(14, _translate("MainWindow", "Luxury Ball"))
        self.sftBallDropdown.setItemText(15, _translate("MainWindow", "Master Ball"))
        self.sftBallDropdown.setItemText(16, _translate("MainWindow", "Moon Ball"))
        self.sftBallDropdown.setItemText(17, _translate("MainWindow", "Nest Ball"))
        self.sftBallDropdown.setItemText(18, _translate("MainWindow", "Net Ball"))
        self.sftBallDropdown.setItemText(19, _translate("MainWindow", "Park Ball"))
        self.sftBallDropdown.setItemText(20, _translate("MainWindow", "Poke Ball"))
        self.sftBallDropdown.setItemText(21, _translate("MainWindow", "Premier Ball"))
        self.sftBallDropdown.setItemText(22, _translate("MainWindow", "Quick Ball"))
        self.sftBallDropdown.setItemText(23, _translate("MainWindow", "Repeat Ball"))
        self.sftBallDropdown.setItemText(24, _translate("MainWindow", "Safari Ball"))
        self.sftBallDropdown.setItemText(25, _translate("MainWindow", "Sport Ball"))
        self.sftBallDropdown.setItemText(26, _translate("MainWindow", "Timer Ball"))
        self.sftBallDropdown.setItemText(27, _translate("MainWindow", "Ultra Ball"))
        self.sftBallLabel.setText(_translate("MainWindow", "Ball"))
        self.sftNatureDropdown.setItemText(1, _translate("MainWindow", "Adamant (+Atk,-SpA)"))
        self.sftNatureDropdown.setItemText(2, _translate("MainWindow", "Bashful (+SpA,-SpA)"))
        self.sftNatureDropdown.setItemText(3, _translate("MainWindow", "Bold (+Def, -Atk)"))
        self.sftNatureDropdown.setItemText(4, _translate("MainWindow", "Brave (+Atk, -Spe)"))
        self.sftNatureDropdown.setItemText(5, _translate("MainWindow", "Calm (+SpD, -Atk)"))
        self.sftNatureDropdown.setItemText(6, _translate("MainWindow", "Careful (+SpD, -SpA)"))
        self.sftNatureDropdown.setItemText(7, _translate("MainWindow", "Docile (+Def, -Def)"))
        self.sftNatureDropdown.setItemText(8, _translate("MainWindow", "Gentle (+SpD, -Def)"))
        self.sftNatureDropdown.setItemText(9, _translate("MainWindow", "Hardy (+Atk, -Atk)"))
        self.sftNatureDropdown.setItemText(10, _translate("MainWindow", "Hasty (+Spe, -Def)"))
        self.sftNatureDropdown.setItemText(11, _translate("MainWindow", "Impish (+Def, -SpA)"))
        self.sftNatureDropdown.setItemText(12, _translate("MainWindow", "Jolly (+Spe, -SpA)"))
        self.sftNatureDropdown.setItemText(13, _translate("MainWindow", "Lax (+Def, -SpD)"))
        self.sftNatureDropdown.setItemText(14, _translate("MainWindow", "Lonely (+Atk, -Def)"))
        self.sftNatureDropdown.setItemText(15, _translate("MainWindow", "Mild (+SpA, -Def)"))
        self.sftNatureDropdown.setItemText(16, _translate("MainWindow", "Modest (+SpA, -Atk)"))
        self.sftNatureDropdown.setItemText(17, _translate("MainWindow", "Naive (+Spe, -SpD)"))
        self.sftNatureDropdown.setItemText(18, _translate("MainWindow", "Naughty (+Atk, -SpD)"))
        self.sftNatureDropdown.setItemText(19, _translate("MainWindow", "Quiet (+SpA, -Spe)"))
        self.sftNatureDropdown.setItemText(20, _translate("MainWindow", "Quirky (+SpD, -SpD)"))
        self.sftNatureDropdown.setItemText(21, _translate("MainWindow", "Rash (+SpA, -SpD)"))
        self.sftNatureDropdown.setItemText(22, _translate("MainWindow", "Relaxed (+Def, -Spe)"))
        self.sftNatureDropdown.setItemText(23, _translate("MainWindow", "Sassy (+SpD, -Spe)"))
        self.sftNatureDropdown.setItemText(24, _translate("MainWindow", "Serious (+Spe, -Spe)"))
        self.sftNatureDropdown.setItemText(25, _translate("MainWindow", "Timid (+Spe, -Atk)"))
        self.sftNatureLabel.setText(_translate("MainWindow", "Nature"))
        self.sftAbilityLabel.setText(_translate("MainWindow", "Ability"))
        self.sftAbilityDropdown.setItemText(1, _translate("MainWindow", "Ability 1"))
        self.sftAbilityDropdown.setItemText(2, _translate("MainWindow", "Ability 2"))
        self.sftAbilityDropdown.setItemText(3, _translate("MainWindow", "Hidden Ability"))
        self.sftGMaxLabel.setText(_translate("MainWindow", "G-Max"))
        self.sftIvBox.setTitle(_translate("MainWindow", "Ivs"))
        self.sftHpRadioButton.setText(_translate("MainWindow", "HP"))
        self.sftAtkRadioButton.setText(_translate("MainWindow", "Atk"))
        self.sftDefRadioButton.setText(_translate("MainWindow", "Def"))
        self.sftSpaRadioButton.setText(_translate("MainWindow", "SpA"))
        self.sftSpdRadioButton.setText(_translate("MainWindow", "SpD"))
        self.sftSpeRadioButton.setText(_translate("MainWindow", "Spe"))
        self.sftZeroSpeedLabel.setText(_translate("MainWindow", "0 Speed"))
        self.sftOtLabel.setText(_translate("MainWindow", "OT"))
        self.sftIdLabel.setText(_translate("MainWindow", "ID"))
        self.sftSubmitPushButton.setText(_translate("MainWindow", "Submit"))
        self.sftObtainedLabel.setText(_translate("MainWindow", "Obtained"))
        self.sftGenderComboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.sftGenderComboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.sftGenderComboBox.setItemText(3, _translate("MainWindow", "Genderless"))
        self.sftGenderLabel.setText(_translate("MainWindow", "Gender"))
        self.sftSTypeComboBox.setItemText(1, _translate("MainWindow", "Star"))
        self.sftSTypeComboBox.setItemText(2, _translate("MainWindow", "Square"))
        self.sftSTypeLabel.setText(_translate("MainWindow", "Shiny Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Shiny For Trade"))
        self.aftBallDropdown.setItemText(1, _translate("MainWindow", "Beast Ball"))
        self.aftBallDropdown.setItemText(2, _translate("MainWindow", "Dream Ball"))
        self.aftBallDropdown.setItemText(3, _translate("MainWindow", "Fast Ball"))
        self.aftBallDropdown.setItemText(4, _translate("MainWindow", "Friend Ball"))
        self.aftBallDropdown.setItemText(5, _translate("MainWindow", "Heavy Ball"))
        self.aftBallDropdown.setItemText(6, _translate("MainWindow", "Level Ball"))
        self.aftBallDropdown.setItemText(7, _translate("MainWindow", "Love Ball"))
        self.aftBallDropdown.setItemText(8, _translate("MainWindow", "Lure Ball"))
        self.aftBallDropdown.setItemText(9, _translate("MainWindow", "Moon Ball"))
        self.aftGMaxLabel.setText(_translate("MainWindow", "G-Max"))
        self.aftAbilityLabel.setText(_translate("MainWindow", "Ability"))
        self.aftNatureLabel.setText(_translate("MainWindow", "Nature"))
        self.aftNatureDropdown.setItemText(1, _translate("MainWindow", "Adamant (+Atk,-SpA)"))
        self.aftNatureDropdown.setItemText(2, _translate("MainWindow", "Bashful (+SpA,-SpA)"))
        self.aftNatureDropdown.setItemText(3, _translate("MainWindow", "Bold (+Def, -Atk)"))
        self.aftNatureDropdown.setItemText(4, _translate("MainWindow", "Brave (+Atk, -Spe)"))
        self.aftNatureDropdown.setItemText(5, _translate("MainWindow", "Calm (+SpD, -Atk)"))
        self.aftNatureDropdown.setItemText(6, _translate("MainWindow", "Careful (+SpD, -SpA)"))
        self.aftNatureDropdown.setItemText(7, _translate("MainWindow", "Docile (+Def, -Def)"))
        self.aftNatureDropdown.setItemText(8, _translate("MainWindow", "Gentle (+SpD, -Def)"))
        self.aftNatureDropdown.setItemText(9, _translate("MainWindow", "Hardy (+Atk, -Atk)"))
        self.aftNatureDropdown.setItemText(10, _translate("MainWindow", "Hasty (+Spe, -Def)"))
        self.aftNatureDropdown.setItemText(11, _translate("MainWindow", "Impish (+Def, -SpA)"))
        self.aftNatureDropdown.setItemText(12, _translate("MainWindow", "Jolly (+Spe, -SpA)"))
        self.aftNatureDropdown.setItemText(13, _translate("MainWindow", "Lax (+Def, -SpD)"))
        self.aftNatureDropdown.setItemText(14, _translate("MainWindow", "Lonely (+Atk, -Def)"))
        self.aftNatureDropdown.setItemText(15, _translate("MainWindow", "Mild (+SpA, -Def)"))
        self.aftNatureDropdown.setItemText(16, _translate("MainWindow", "Modest (+SpA, -Atk)"))
        self.aftNatureDropdown.setItemText(17, _translate("MainWindow", "Naive (+Spe, -SpD)"))
        self.aftNatureDropdown.setItemText(18, _translate("MainWindow", "Naughty (+Atk, -SpD)"))
        self.aftNatureDropdown.setItemText(19, _translate("MainWindow", "Quiet (+SpA, -Spe)"))
        self.aftNatureDropdown.setItemText(20, _translate("MainWindow", "Quirky (+SpD, -SpD)"))
        self.aftNatureDropdown.setItemText(21, _translate("MainWindow", "Rash (+SpA, -SpD)"))
        self.aftNatureDropdown.setItemText(22, _translate("MainWindow", "Relaxed (+Def, -Spe)"))
        self.aftNatureDropdown.setItemText(23, _translate("MainWindow", "Sassy (+SpD, -Spe)"))
        self.aftNatureDropdown.setItemText(24, _translate("MainWindow", "Serious (+Spe, -Spe)"))
        self.aftNatureDropdown.setItemText(25, _translate("MainWindow", "Timid (+Spe, -Atk)"))
        self.aftZeroSpeedLabel.setText(_translate("MainWindow", "0 Speed"))
        self.aftSubmitPushButton.setText(_translate("MainWindow", "Submit"))
        self.aftAbilityDropdown.setItemText(1, _translate("MainWindow", "Ability 1"))
        self.aftAbilityDropdown.setItemText(2, _translate("MainWindow", "Ability 2"))
        self.aftAbilityDropdown.setItemText(3, _translate("MainWindow", "Hidden Ability"))
        self.aftBallLabel.setText(_translate("MainWindow", "Ball"))
        self.aftIvDropdown.setItemText(1, _translate("MainWindow", "0"))
        self.aftIvDropdown.setItemText(2, _translate("MainWindow", "1"))
        self.aftIvDropdown.setItemText(3, _translate("MainWindow", "2"))
        self.aftIvDropdown.setItemText(4, _translate("MainWindow", "3"))
        self.aftIvDropdown.setItemText(5, _translate("MainWindow", "4"))
        self.aftIvDropdown.setItemText(6, _translate("MainWindow", "5"))
        self.aftIvDropdown.setItemText(7, _translate("MainWindow", "6"))
        self.aftIvLabel.setText(_translate("MainWindow", "Ivs"))
        self.aftStockLabel.setText(_translate("MainWindow", "Stock"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Aprimon For Trade"))
        self.shinyIvBox.setTitle(_translate("MainWindow", "Ivs"))
        self.shinyHpRadioButton.setText(_translate("MainWindow", "HP"))
        self.shinyAtkRadioButton.setText(_translate("MainWindow", "Atk"))
        self.shinyDefRadioButton.setText(_translate("MainWindow", "Def"))
        self.shinySpaRadioButton.setText(_translate("MainWindow", "SpA"))
        self.shinySpdRadioButton.setText(_translate("MainWindow", "SpD"))
        self.shinySpeRadioButton.setText(_translate("MainWindow", "Spe"))
        self.shinyAbilityLabel.setText(_translate("MainWindow", "Ability"))
        self.shinyGMaxLabel.setText(_translate("MainWindow", "G-Max"))
        self.shinyZeroSpeedLabel.setText(_translate("MainWindow", "0 Speed"))
        self.shinyBallLabel.setText(_translate("MainWindow", "Ball"))
        self.shinyNatureDropdown.setItemText(1, _translate("MainWindow", "Adamant (+Atk,-SpA)"))
        self.shinyNatureDropdown.setItemText(2, _translate("MainWindow", "Bashful (+SpA,-SpA)"))
        self.shinyNatureDropdown.setItemText(3, _translate("MainWindow", "Bold (+Def, -Atk)"))
        self.shinyNatureDropdown.setItemText(4, _translate("MainWindow", "Brave (+Atk, -Spe)"))
        self.shinyNatureDropdown.setItemText(5, _translate("MainWindow", "Calm (+SpD, -Atk)"))
        self.shinyNatureDropdown.setItemText(6, _translate("MainWindow", "Careful (+SpD, -SpA)"))
        self.shinyNatureDropdown.setItemText(7, _translate("MainWindow", "Docile (+Def, -Def)"))
        self.shinyNatureDropdown.setItemText(8, _translate("MainWindow", "Gentle (+SpD, -Def)"))
        self.shinyNatureDropdown.setItemText(9, _translate("MainWindow", "Hardy (+Atk, -Atk)"))
        self.shinyNatureDropdown.setItemText(10, _translate("MainWindow", "Hasty (+Spe, -Def)"))
        self.shinyNatureDropdown.setItemText(11, _translate("MainWindow", "Impish (+Def, -SpA)"))
        self.shinyNatureDropdown.setItemText(12, _translate("MainWindow", "Jolly (+Spe, -SpA)"))
        self.shinyNatureDropdown.setItemText(13, _translate("MainWindow", "Lax (+Def, -SpD)"))
        self.shinyNatureDropdown.setItemText(14, _translate("MainWindow", "Lonely (+Atk, -Def)"))
        self.shinyNatureDropdown.setItemText(15, _translate("MainWindow", "Mild (+SpA, -Def)"))
        self.shinyNatureDropdown.setItemText(16, _translate("MainWindow", "Modest (+SpA, -Atk)"))
        self.shinyNatureDropdown.setItemText(17, _translate("MainWindow", "Naive (+Spe, -SpD)"))
        self.shinyNatureDropdown.setItemText(18, _translate("MainWindow", "Naughty (+Atk, -SpD)"))
        self.shinyNatureDropdown.setItemText(19, _translate("MainWindow", "Quiet (+SpA, -Spe)"))
        self.shinyNatureDropdown.setItemText(20, _translate("MainWindow", "Quirky (+SpD, -SpD)"))
        self.shinyNatureDropdown.setItemText(21, _translate("MainWindow", "Rash (+SpA, -SpD)"))
        self.shinyNatureDropdown.setItemText(22, _translate("MainWindow", "Relaxed (+Def, -Spe)"))
        self.shinyNatureDropdown.setItemText(23, _translate("MainWindow", "Sassy (+SpD, -Spe)"))
        self.shinyNatureDropdown.setItemText(24, _translate("MainWindow", "Serious (+Spe, -Spe)"))
        self.shinyNatureDropdown.setItemText(25, _translate("MainWindow", "Timid (+Spe, -Atk)"))
        self.shinySubmitPushButton.setText(_translate("MainWindow", "Submit"))
        self.shinyAbilityDropdown.setItemText(1, _translate("MainWindow", "Ability 1"))
        self.shinyAbilityDropdown.setItemText(2, _translate("MainWindow", "Ability 2"))
        self.shinyAbilityDropdown.setItemText(3, _translate("MainWindow", "Hidden Ability"))
        self.shinyBallDropdown.setItemText(1, _translate("MainWindow", "Beast Ball"))
        self.shinyBallDropdown.setItemText(2, _translate("MainWindow", "Cherish Ball"))
        self.shinyBallDropdown.setItemText(3, _translate("MainWindow", "Dive Ball"))
        self.shinyBallDropdown.setItemText(4, _translate("MainWindow", "Dream Ball"))
        self.shinyBallDropdown.setItemText(5, _translate("MainWindow", "Dusk Ball"))
        self.shinyBallDropdown.setItemText(6, _translate("MainWindow", "Fast Ball"))
        self.shinyBallDropdown.setItemText(7, _translate("MainWindow", "Friend Ball"))
        self.shinyBallDropdown.setItemText(8, _translate("MainWindow", "Great Ball"))
        self.shinyBallDropdown.setItemText(9, _translate("MainWindow", "Heal Ball"))
        self.shinyBallDropdown.setItemText(10, _translate("MainWindow", "Heavy Ball"))
        self.shinyBallDropdown.setItemText(11, _translate("MainWindow", "Level Ball"))
        self.shinyBallDropdown.setItemText(12, _translate("MainWindow", "Love Ball"))
        self.shinyBallDropdown.setItemText(13, _translate("MainWindow", "Lure Ball"))
        self.shinyBallDropdown.setItemText(14, _translate("MainWindow", "Luxury Ball"))
        self.shinyBallDropdown.setItemText(15, _translate("MainWindow", "Master Ball"))
        self.shinyBallDropdown.setItemText(16, _translate("MainWindow", "Moon Ball"))
        self.shinyBallDropdown.setItemText(17, _translate("MainWindow", "Nest Ball"))
        self.shinyBallDropdown.setItemText(18, _translate("MainWindow", "Net Ball"))
        self.shinyBallDropdown.setItemText(19, _translate("MainWindow", "Park Ball"))
        self.shinyBallDropdown.setItemText(20, _translate("MainWindow", "Poke Ball"))
        self.shinyBallDropdown.setItemText(21, _translate("MainWindow", "Premier Ball"))
        self.shinyBallDropdown.setItemText(22, _translate("MainWindow", "Quick Ball"))
        self.shinyBallDropdown.setItemText(23, _translate("MainWindow", "Repeat Ball"))
        self.shinyBallDropdown.setItemText(24, _translate("MainWindow", "Safari Ball"))
        self.shinyBallDropdown.setItemText(25, _translate("MainWindow", "Sport Ball"))
        self.shinyBallDropdown.setItemText(26, _translate("MainWindow", "Timer Ball"))
        self.shinyBallDropdown.setItemText(27, _translate("MainWindow", "Ultra Ball"))
        self.shinyNatureLabel.setText(_translate("MainWindow", "Nature"))
        self.shinyNicknameLabel.setText(_translate("MainWindow", "Nickname"))
        self.shinySTypeLabel.setText(_translate("MainWindow", "Shiny Type"))
        self.shinySTypeComboBox.setItemText(1, _translate("MainWindow", "Star"))
        self.shinySTypeComboBox.setItemText(2, _translate("MainWindow", "Square"))
        self.shinyGenderLabel.setText(_translate("MainWindow", "Gender"))
        self.shinyGenderComboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.shinyGenderComboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.shinyGenderComboBox.setItemText(3, _translate("MainWindow", "Genderless"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Shiny"))
        self.battleAbilityLabel.setText(_translate("MainWindow", "Ability"))
        self.battleBallDropdown.setItemText(1, _translate("MainWindow", "Beast Ball"))
        self.battleBallDropdown.setItemText(2, _translate("MainWindow", "Cherish Ball"))
        self.battleBallDropdown.setItemText(3, _translate("MainWindow", "Dive Ball"))
        self.battleBallDropdown.setItemText(4, _translate("MainWindow", "Dream Ball"))
        self.battleBallDropdown.setItemText(5, _translate("MainWindow", "Dusk Ball"))
        self.battleBallDropdown.setItemText(6, _translate("MainWindow", "Fast Ball"))
        self.battleBallDropdown.setItemText(7, _translate("MainWindow", "Friend Ball"))
        self.battleBallDropdown.setItemText(8, _translate("MainWindow", "Great Ball"))
        self.battleBallDropdown.setItemText(9, _translate("MainWindow", "Heal Ball"))
        self.battleBallDropdown.setItemText(10, _translate("MainWindow", "Heavy Ball"))
        self.battleBallDropdown.setItemText(11, _translate("MainWindow", "Level Ball"))
        self.battleBallDropdown.setItemText(12, _translate("MainWindow", "Love Ball"))
        self.battleBallDropdown.setItemText(13, _translate("MainWindow", "Lure Ball"))
        self.battleBallDropdown.setItemText(14, _translate("MainWindow", "Luxury Ball"))
        self.battleBallDropdown.setItemText(15, _translate("MainWindow", "Master Ball"))
        self.battleBallDropdown.setItemText(16, _translate("MainWindow", "Moon Ball"))
        self.battleBallDropdown.setItemText(17, _translate("MainWindow", "Nest Ball"))
        self.battleBallDropdown.setItemText(18, _translate("MainWindow", "Net Ball"))
        self.battleBallDropdown.setItemText(19, _translate("MainWindow", "Park Ball"))
        self.battleBallDropdown.setItemText(20, _translate("MainWindow", "Poke Ball"))
        self.battleBallDropdown.setItemText(21, _translate("MainWindow", "Premier Ball"))
        self.battleBallDropdown.setItemText(22, _translate("MainWindow", "Quick Ball"))
        self.battleBallDropdown.setItemText(23, _translate("MainWindow", "Repeat Ball"))
        self.battleBallDropdown.setItemText(24, _translate("MainWindow", "Safari Ball"))
        self.battleBallDropdown.setItemText(25, _translate("MainWindow", "Sport Ball"))
        self.battleBallDropdown.setItemText(26, _translate("MainWindow", "Timer Ball"))
        self.battleBallDropdown.setItemText(27, _translate("MainWindow", "Ultra Ball"))
        self.battleNatureLabel.setText(_translate("MainWindow", "Nature"))
        self.battleZeroSpeedLabel.setText(_translate("MainWindow", "0 Speed"))
        self.battleNatureDropdown.setItemText(1, _translate("MainWindow", "Adamant (+Atk,-SpA)"))
        self.battleNatureDropdown.setItemText(2, _translate("MainWindow", "Bashful (+SpA,-SpA)"))
        self.battleNatureDropdown.setItemText(3, _translate("MainWindow", "Bold (+Def, -Atk)"))
        self.battleNatureDropdown.setItemText(4, _translate("MainWindow", "Brave (+Atk, -Spe)"))
        self.battleNatureDropdown.setItemText(5, _translate("MainWindow", "Calm (+SpD, -Atk)"))
        self.battleNatureDropdown.setItemText(6, _translate("MainWindow", "Careful (+SpD, -SpA)"))
        self.battleNatureDropdown.setItemText(7, _translate("MainWindow", "Docile (+Def, -Def)"))
        self.battleNatureDropdown.setItemText(8, _translate("MainWindow", "Gentle (+SpD, -Def)"))
        self.battleNatureDropdown.setItemText(9, _translate("MainWindow", "Hardy (+Atk, -Atk)"))
        self.battleNatureDropdown.setItemText(10, _translate("MainWindow", "Hasty (+Spe, -Def)"))
        self.battleNatureDropdown.setItemText(11, _translate("MainWindow", "Impish (+Def, -SpA)"))
        self.battleNatureDropdown.setItemText(12, _translate("MainWindow", "Jolly (+Spe, -SpA)"))
        self.battleNatureDropdown.setItemText(13, _translate("MainWindow", "Lax (+Def, -SpD)"))
        self.battleNatureDropdown.setItemText(14, _translate("MainWindow", "Lonely (+Atk, -Def)"))
        self.battleNatureDropdown.setItemText(15, _translate("MainWindow", "Mild (+SpA, -Def)"))
        self.battleNatureDropdown.setItemText(16, _translate("MainWindow", "Modest (+SpA, -Atk)"))
        self.battleNatureDropdown.setItemText(17, _translate("MainWindow", "Naive (+Spe, -SpD)"))
        self.battleNatureDropdown.setItemText(18, _translate("MainWindow", "Naughty (+Atk, -SpD)"))
        self.battleNatureDropdown.setItemText(19, _translate("MainWindow", "Quiet (+SpA, -Spe)"))
        self.battleNatureDropdown.setItemText(20, _translate("MainWindow", "Quirky (+SpD, -SpD)"))
        self.battleNatureDropdown.setItemText(21, _translate("MainWindow", "Rash (+SpA, -SpD)"))
        self.battleNatureDropdown.setItemText(22, _translate("MainWindow", "Relaxed (+Def, -Spe)"))
        self.battleNatureDropdown.setItemText(23, _translate("MainWindow", "Sassy (+SpD, -Spe)"))
        self.battleNatureDropdown.setItemText(24, _translate("MainWindow", "Serious (+Spe, -Spe)"))
        self.battleNatureDropdown.setItemText(25, _translate("MainWindow", "Timid (+Spe, -Atk)"))
        self.battleGMaxLabel.setText(_translate("MainWindow", "G-Max"))
        self.battleAbilityDropdown.setItemText(1, _translate("MainWindow", "Ability 1"))
        self.battleAbilityDropdown.setItemText(2, _translate("MainWindow", "Ability 2"))
        self.battleAbilityDropdown.setItemText(3, _translate("MainWindow", "Hidden Ability"))
        self.battleBallLabel.setText(_translate("MainWindow", "Ball"))
        self.battleIvBox.setTitle(_translate("MainWindow", "Ivs"))
        self.battleHpRadioButton.setText(_translate("MainWindow", "HP"))
        self.battleAtkRadioButton.setText(_translate("MainWindow", "Atk"))
        self.battleDefRadioButton.setText(_translate("MainWindow", "Def"))
        self.battleSpaRadioButton.setText(_translate("MainWindow", "SpA"))
        self.battleSpdRadioButton.setText(_translate("MainWindow", "SpD"))
        self.battleSpeRadioButton.setText(_translate("MainWindow", "Spe"))
        self.battleNicknameLabel.setText(_translate("MainWindow", "Nickname"))
        self.battleSubmitPushButton.setText(_translate("MainWindow", "Submit"))
        self.battleShinyLabel.setText(_translate("MainWindow", "Shiny"))
        self.battleMovesGroupBox.setTitle(_translate("MainWindow", "Moves"))
        self.battleMove1Label.setText(_translate("MainWindow", "Move 1"))
        self.battleMove2Label.setText(_translate("MainWindow", "Move 2"))
        self.battleMove3Label.setText(_translate("MainWindow", "Move 3"))
        self.battleMove4Label.setText(_translate("MainWindow", "Move 4"))
        self.battleSTypeLabel.setText(_translate("MainWindow", "Shiny Type"))
        self.battleSTypeComboBox.setItemText(1, _translate("MainWindow", "Star"))
        self.battleSTypeComboBox.setItemText(2, _translate("MainWindow", "Square"))
        self.battleGenderLabel.setText(_translate("MainWindow", "Gender"))
        self.battleGenderComboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.battleGenderComboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.battleGenderComboBox.setItemText(3, _translate("MainWindow", "Genderless"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Battler/Keep"))
        self.updateRowsButton.setText(_translate("MainWindow", "Update Free Rows"))
